// Public API of @morphir/ui — exports accumulate as modules land.
export * from './state/shell-state.svelte.ts'
export { default as Icon, type IconName } from './icons/Icon.svelte'
export { default as AppShell } from './shell/AppShell.svelte'
export { default as Titlebar } from './shell/Titlebar.svelte'
export { default as WorkbenchRail } from './shell/WorkbenchRail.svelte'
export { default as WorkbenchTabs } from './shell/WorkbenchTabs.svelte'
export * from './services/token.ts'
export * from './services/config.ts'
export * from './services/services.ts'
export * from './services/pipeline.ts'
export * from './workbench/types.ts'
export * from './workbench/project-model-state.ts'
export * from './workbench/services.ts'
export * from './workbench/provider-router.ts'
export * from './workbench/workflows.ts'
export { WorkbenchStore } from './workbench/workbench-store.svelte.ts'
export { default as MorphirApp } from './shell/MorphirApp.svelte'
export { default as OverviewView } from './views/OverviewView.svelte'
export { default as IrExplorerView } from './views/IrExplorerView.svelte'
export { default as WorkbenchView } from './views/WorkbenchView.svelte'
export { default as DevelopmentWorkbenchView } from './views/DevelopmentWorkbenchView.svelte'
export { default as WorkbenchErrorView } from './views/WorkbenchErrorView.svelte'
export { default as SettingsView } from './views/settings/SettingsView.svelte'
export { default as XRayView } from './views/insight/XRayView.svelte'
export { default as DefinitionDetail } from './views/insight/DefinitionDetail.svelte'
export { default as InsightView } from './views/insight/InsightView.svelte'
export type { InspectMeta } from './views/insight/insight-context.ts'
